apiVersion: graphql.gloo.solo.io/v1alpha1
kind: GraphQLApi
metadata:
  name: bookinfo-graphql
  namespace: gloo-system
spec:
  executableSchema:
    executor:
      local:
        enableIntrospection: true
        resolutions:
          Query|productsForHome:
            restResolver:
              request:
                headers:
                  :method: GET
                  :path: /api/v1/products
              upstreamRef:
                name: default-productpage-9080
                namespace: gloo-system
          product_details:
            restResolver:
              request:
                headers:
                  :method: GET
                  :path: /details/{$parent.id}
              upstreamRef:
                name: default-details-9080
                namespace: gloo-system
          ratings:
            restResolver:
              request:
                headers:
                  :method: GET
                  :path: /ratings/{$parent.id}
              response:
                resultRoot: "ratings[*]"
                setters:
                  reviewer: "{$body[*][0]}"
                  numStars: "{$body[*][1]}"
              upstreamRef:
                name: default-ratings-9080
                namespace: gloo-system
    schemaDefinition: |
      type Query {
        """Description of a book in HTML"""
        productsForHome: [Product] @resolve(name: "Query|productsForHome")
      }

      """Each book has a product entry"""
      type Product {
        """Unique identifier for books"""
      id: String
      """The book title"""
      title: String
      """Description of a book in HTML"""
      descriptionHtml: String
      """Product details"""
      details: ProductDetails @resolve(name: "product_details")
      """List of reader reviews for this book"""
      review: [Review] @resolve(name: "review")
      """List of reader ratings for this book"""
      ratings: [Rating]
      }

      type ProductDetails {
        """Author of the book"""
        author: String
        """Total number of pages in the book"""
        pages: Int
        """Year of original publication"""
        year: Int
      }

      """A book review"""
      type Review {
          """Name of the reviewer"""
          reviewer: String
          """Review details"""
          text: String
      }

      """A book rating"""
      type Rating {
          """Name of the user peforming the rating"""
          reviewer: String
          """Number of stars for this rating"""
          numStars: Int
      }
